---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard
  labels:
    app: leaderboard
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30182
  selector:
    app: leaderboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leaderboard
  labels:
    app: leaderboard
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: taiponrock/kitura-leaderboards:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: POSTGRES_USER
