---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ibm-fitchain-com
  namespace: default
spec:
  secretName: ibm-fitchain-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: www.ibm-fitchain.com
  dnsNames:
    - www.ibm-fitchain.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - www.ibm-fitchain.com
      - http01:
          ingress: my-ingress
        domains:
          - www.ibm-fitchain.com
